include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_build_context_synchronously: false

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 5
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - always-remove-listener
    - avoid-border-all
    - avoid-collection-methods-with-unrelated-types
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-wrapping-in-padding
    - avoid-unused-parameters
    - avoid-global-state
    - prefer-conditional-expressions
    - prefer-correct-edge-insets-constructor
    - prefer-extracting-callbacks
    - prefer-match-file-name
    - prefer-last
    - prefer-first
    - prefer-immediate-return
    - prefer-correct-test-file-name
    - prefer-conditional-expressions
    - prefer-commenting-analyzer-ignores
    - no-boolean-literal-compare
    - no-equal-then-else
