name: wellbeing_checkup
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  flutter_flavor: ^3.1.1
  go_router: ^7.0.1
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true

  assets:
    - assets/images/ 
    - assets/icons/
    - assets/data/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
